---
- name: create docker working directory
  file:
    path: "{{ usenet_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create sabnzbd config volume directory
  file:
    path: "{{ usenet_sabnzbd_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create sabnzbd downloads volume directory
  file:
    path: "{{ usenet_sabnzbd_downloads_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750
- name: create sabnzbd incomplete downloads volume directory
  file:
    path: "{{ usenet_sabnzbd_incomplete_downloads_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create sonarr config volume directory
  file:
    path: "{{ usenet_sonarr_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create sonarr tv volume directory
  file:
    path: "{{ usenet_sonarr_tv_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create sonarr downloads volume directory
  file:
    path: "{{ usenet_sonarr_downloads_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ usenet_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart usenet service

- name: Create systemd unit file
  template:
    src: usenet.systemd.j2
    dest: "/etc/systemd/system/{{ usenet_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart usenet service

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start systemd service (if not started)
  service:
    name: "{{ usenet_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
