---
- name: create docker working directory
  file:
    path: "{{ usenet_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create sabnzbd config volume directory
  file:
    path: "{{ usenet_sabnzbd_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create downloads volume directory
  file:
    path: "{{ usenet_downloads_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create incomplete downloads volume directory
  file:
    path: "{{ usenet_incomplete_downloads_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create sonarr config volume directory
  file:
    path: "{{ usenet_sonarr_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create radarr config volume directory
  file:
    path: "{{ usenet_radarr_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create lidarr config volume directory
  file:
    path: "{{ usenet_lidarr_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create bazarr config volume directory
  file:
    path: "{{ usenet_bazarr_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create tv volume directory
  file:
    path: "{{ usenet_tv_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0755

- name: create movies volume directory
  file:
    path: "{{ usenet_movies_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0755

- name: create music volume directory
  file:
    path: "{{ usenet_music_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0755

- name: create nzbhydra2 config volume directory
  file:
    path: "{{ usenet_nzbhydra2_config_volume_directory }}"
    state: directory
    owner: "{{ usenet_user_id | int }}"
    group: "{{ usenet_group_id | int }}"
    mode: 0750

- name: create vpn config volume directory
  file:
    path: "{{ usenet_vpn_config_volume_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  when: usenet_vpn_enabled | bool

- name: create private volume directory
  file:
    path: "{{ usenet_vpn_private_volume_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: usenet_vpn_enabled | bool

- name: create private credentials file
  template:
    src: credentials.env.j2
    dest: "{{ usenet_vpn_private_credentials_file_path }}"
    owner: root
    group: root
    mode: 0700
  when: usenet_vpn_enabled | bool
  notify: Restart usenet service

- name: create vpn server certificate file
  copy:
    dest: "{{ usenet_vpn_server_certificate_path }}"
    content: "{{ usenet_vpn_ca_cert }}"
    owner: root
    group: root
    mode: 0644
  when: usenet_vpn_enabled | bool
  notify: Restart usenet service

- name: template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ usenet_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart usenet service

- name: Create systemd unit file
  template:
    src: usenet.systemd.j2
    dest: "/etc/systemd/system/{{ usenet_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart usenet service

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start systemd service (if not started)
  service:
    name: "{{ usenet_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
