---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/usenet/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: "3.2"
          services:
            sabnzbd:
              image: ghcr.io/linuxserver/sabnzbd:latest
              container_name: sabnzbd
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/usenet/sabnzbd/config:/config
                - /srv/usenet/sabnzbd/downloads:/downloads
                - /srv/usenet/sabnzbd/incomplete-downloads:/incomplete-downloads
              ports:
                - 0.0.0.0:8080:8080
                - 0.0.0.0:9090:9090
              restart: unless-stopped

            sonarr:
              image: ghcr.io/linuxserver/sonarr:latest
              container_name: sonarr
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              depends_on:
                - sabnzbd
              volumes:
                - /srv/usenet/sonarr/config:/config
                - /srv/usenet/sonarr/tv:/tv
                - /srv/usenet/sonarr/downloads:/downloads
              ports:
                - 0.0.0.0:8989:8989
              restart: unless-stopped

            radarr:
              image: ghcr.io/linuxserver/radarr:latest
              container_name: radarr
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/usenet/radarr/config:/config
                - /srv/usenet/radarr/movies:/movies
                - /srv/usenet/radarr/downloads:/downloads
              ports:
                - 0.0.0.0:7878:7878
              restart: unless-stopped

            bazarr:
              image: ghcr.io/linuxserver/bazarr:latest
              container_name: bazarr
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/usenet/bazarr/config:/config
                - /srv/usenet/bazarr/movies:/movies
                - /srv/usenet/bazarr/tv:/tv
              ports:
                - 0.0.0.0:6767:6767
              restart: unless-stopped

    - name: Should create sabnzbd config volume
      stat:
        path: /srv/usenet/sabnzbd/config
      register: sabnzbd_config_volume_directory
      failed_when: not (
        sabnzbd_config_volume_directory.stat.exists
        and sabnzbd_config_volume_directory.stat.uid == 666
        and sabnzbd_config_volume_directory.stat.gid == 666
        and sabnzbd_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sabnzbd downloads volume
      stat:
        path: /srv/usenet/sabnzbd/downloads
      register: sabnzbd_downloads_volume_directory
      failed_when: not (
        sabnzbd_downloads_volume_directory.stat.exists
        and sabnzbd_downloads_volume_directory.stat.uid == 666
        and sabnzbd_downloads_volume_directory.stat.gid == 666
        and sabnzbd_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create sabnzbd incomplete downloads volume
      stat:
        path: /srv/usenet/sabnzbd/downloads
      register: sabnzbd_incomplete_downloads_volume_directory
      failed_when: not (
        sabnzbd_incomplete_downloads_volume_directory.stat.exists
        and sabnzbd_incomplete_downloads_volume_directory.stat.uid == 666
        and sabnzbd_incomplete_downloads_volume_directory.stat.gid == 666
        and sabnzbd_incomplete_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr config volume
      stat:
        path: /srv/usenet/sonarr/config
      register: sonarr_config_volume_directory
      failed_when: not (
        sonarr_config_volume_directory.stat.exists
        and sonarr_config_volume_directory.stat.uid == 666
        and sonarr_config_volume_directory.stat.gid == 666
        and sonarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr tv volume
      stat:
        path: /srv/usenet/sonarr/tv
      register: sonarr_tv_volume_directory
      failed_when: not (
        sonarr_tv_volume_directory.stat.exists
        and sonarr_tv_volume_directory.stat.uid == 666
        and sonarr_tv_volume_directory.stat.gid == 666
        and sonarr_tv_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr downloads volume
      stat:
        path: /srv/usenet/sonarr/downloads
      register: sonarr_downloads_volume_directory
      failed_when: not (
        sonarr_downloads_volume_directory.stat.exists
        and sonarr_downloads_volume_directory.stat.uid == 666
        and sonarr_downloads_volume_directory.stat.gid == 666
        and sonarr_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr config volume
      stat:
        path: /srv/usenet/radarr/config
      register: radarr_config_volume_directory
      failed_when: not (
        radarr_config_volume_directory.stat.exists
        and radarr_config_volume_directory.stat.uid == 666
        and radarr_config_volume_directory.stat.gid == 666
        and radarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr movies volume
      stat:
        path: /srv/usenet/radarr/movies
      register: radarr_movies_volume_directory
      failed_when: not (
        radarr_movies_volume_directory.stat.exists
        and radarr_movies_volume_directory.stat.uid == 666
        and radarr_movies_volume_directory.stat.gid == 666
        and radarr_movies_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr downloads volume
      stat:
        path: /srv/usenet/radarr/downloads
      register: radarr_downloads_volume_directory
      failed_when: not (
        radarr_downloads_volume_directory.stat.exists
        and radarr_downloads_volume_directory.stat.uid == 666
        and radarr_downloads_volume_directory.stat.gid == 666
        and radarr_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr config volume
      stat:
        path: /srv/usenet/bazarr/config
      register: bazarr_config_volume_directory
      failed_when: not (
        bazarr_config_volume_directory.stat.exists
        and bazarr_config_volume_directory.stat.uid == 666
        and bazarr_config_volume_directory.stat.gid == 666
        and bazarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr tv volume
      stat:
        path: /srv/usenet/bazarr/tv
      register: bazarr_tv_volume_directory
      failed_when: not (
        bazarr_tv_volume_directory.stat.exists
        and bazarr_tv_volume_directory.stat.uid == 666
        and bazarr_tv_volume_directory.stat.gid == 666
        and bazarr_tv_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr movies volume
      stat:
        path: /srv/usenet/bazarr/movies
      register: bazarr_movies_volume_directory
      failed_when: not (
        bazarr_movies_volume_directory.stat.exists
        and bazarr_movies_volume_directory.stat.uid == 666
        and bazarr_movies_volume_directory.stat.gid == 666
        and bazarr_movies_volume_directory.stat.mode == '0750'
        )

    - name: Should usenet systemd unit file
      slurp:
        src: /etc/systemd/system/usenet.service
      register: usenet_service_file
      failed_when:
        not usenet_service_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=usenet service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          ExecStartPre=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            pull

          ExecStart=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            up

          ExecStop=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          Restart=always
          RestartSec=60s
          TimeoutSec=3600

    - name: Should open 8080/tcp port
      command: nc -z -w1 localhost 8080
      changed_when: false
      register: netcat_8080
      retries: 300
      delay: 1
      until: netcat_8080 is defined
        and netcat_8080.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 8989/tcp port
      command: nc -z -w1 localhost 8989
      changed_when: false
      register: netcat_8989
      retries: 300
      delay: 1
      until: netcat_8989 is defined
        and netcat_8989.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 7878/tcp port
      command: nc -z -w1 localhost 7878
      changed_when: false
      register: netcat_7878
      retries: 300
      delay: 1
      until: netcat_7878 is defined
        and netcat_7878.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 6767/tcp port
      command: nc -z -w1 localhost 6767
      changed_when: false
      register: netcat_6767
      retries: 300
      delay: 1
      until: netcat_6767 is defined
        and netcat_6767.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )
