---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/usenet/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: "3.2"
          services:
            sabnzbd:
              image: ghcr.io/linuxserver/sabnzbd:version-3.1.1
              container_name: sabnzbd
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/sabnzbd/config:/config
                - /srv/my_usenet/sabnzbd/downloads:/downloads
                - /srv/my_usenet/sabnzbd/incomplete-downloads:/incomplete-downloads
              ports:
                - 127.0.0.1:18080:8080
                - 127.0.0.1:19090:9090
              restart: unless-stopped

            sonarr:
              image: ghcr.io/linuxserver/sonarr:version-2.0.0.5344
              container_name: sonarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              depends_on:
                - sabnzbd
              volumes:
                - /srv/my_usenet/sonarr/config:/config
                - /srv/my_usenet/sonarr/tv:/tv
                - /srv/my_usenet/sonarr/downloads:/downloads
              ports:
                - 127.0.0.1:18989:8989
              restart: unless-stopped

            radarr:
              image: ghcr.io/linuxserver/radarr:version-3.0.0.4127
              container_name: radarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/radarr/config:/config
                - /srv/my_usenet/radarr/movies:/movies
                - /srv/my_usenet/radarr/downloads:/downloads
              ports:
                - 127.0.0.1:17878:7878
              restart: unless-stopped

            bazarr:
              image: ghcr.io/linuxserver/bazarr:version-v0.9.0.6
              container_name: bazarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/bazarr/config:/config
                - /srv/my_usenet/bazarr/movies:/movies
                - /srv/my_usenet/bazarr/tv:/tv
              ports:
                - 127.0.0.1:16767:6767
              restart: unless-stopped

            nzbhydra2:
              image: ghcr.io/linuxserver/nzbhydra2:version-v3.5.1
              container_name: nzbhydra2
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
              volumes:
                - /srv/my_usenet/nzbhydra2/config:/config
                - /srv/my_usenet/nzbhydra2/downloads:/downloads
              ports:
                - 127.0.0.1:15076:5076
              restart: unless-stopped

    - name: Should create sabnzbd config volume
      stat:
        path: /srv/my_usenet/sabnzbd/config
      register: sabnzbd_config_volume_directory
      failed_when: not (
        sabnzbd_config_volume_directory.stat.exists
        and sabnzbd_config_volume_directory.stat.uid == 777
        and sabnzbd_config_volume_directory.stat.gid == 888
        and sabnzbd_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sabnzbd downloads volume
      stat:
        path: /srv/my_usenet/sabnzbd/downloads
      register: sabnzbd_downloads_volume_directory
      failed_when: not (
        sabnzbd_downloads_volume_directory.stat.exists
        and sabnzbd_downloads_volume_directory.stat.uid == 777
        and sabnzbd_downloads_volume_directory.stat.gid == 888
        and sabnzbd_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create sabnzbd incomplete downloads volume
      stat:
        path: /srv/my_usenet/sabnzbd/downloads
      register: sabnzbd_incomplete_downloads_volume_directory
      failed_when: not (
        sabnzbd_incomplete_downloads_volume_directory.stat.exists
        and sabnzbd_incomplete_downloads_volume_directory.stat.uid == 777
        and sabnzbd_incomplete_downloads_volume_directory.stat.gid == 888
        and sabnzbd_incomplete_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr config volume
      stat:
        path: /srv/my_usenet/sonarr/config
      register: sonarr_config_volume_directory
      failed_when: not (
        sonarr_config_volume_directory.stat.exists
        and sonarr_config_volume_directory.stat.uid == 777
        and sonarr_config_volume_directory.stat.gid == 888
        and sonarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr tv volume
      stat:
        path: /srv/my_usenet/sonarr/tv
      register: sonarr_tv_volume_directory
      failed_when: not (
        sonarr_tv_volume_directory.stat.exists
        and sonarr_tv_volume_directory.stat.uid == 777
        and sonarr_tv_volume_directory.stat.gid == 888
        and sonarr_tv_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr downloads volume
      stat:
        path: /srv/my_usenet/sonarr/downloads
      register: sonarr_downloads_volume_directory
      failed_when: not (
        sonarr_downloads_volume_directory.stat.exists
        and sonarr_downloads_volume_directory.stat.uid == 777
        and sonarr_downloads_volume_directory.stat.gid == 888
        and sonarr_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr config volume
      stat:
        path: /srv/my_usenet/radarr/config
      register: radarr_config_volume_directory
      failed_when: not (
        radarr_config_volume_directory.stat.exists
        and radarr_config_volume_directory.stat.uid == 777
        and radarr_config_volume_directory.stat.gid == 888
        and radarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr movies volume
      stat:
        path: /srv/my_usenet/radarr/movies
      register: radarr_movies_volume_directory
      failed_when: not (
        radarr_movies_volume_directory.stat.exists
        and radarr_movies_volume_directory.stat.uid == 777
        and radarr_movies_volume_directory.stat.gid == 888
        and radarr_movies_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr downloads volume
      stat:
        path: /srv/my_usenet/radarr/downloads
      register: radarr_downloads_volume_directory
      failed_when: not (
        radarr_downloads_volume_directory.stat.exists
        and radarr_downloads_volume_directory.stat.uid == 777
        and radarr_downloads_volume_directory.stat.gid == 888
        and radarr_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr config volume
      stat:
        path: /srv/my_usenet/bazarr/config
      register: bazarr_config_volume_directory
      failed_when: not (
        bazarr_config_volume_directory.stat.exists
        and bazarr_config_volume_directory.stat.uid == 777
        and bazarr_config_volume_directory.stat.gid == 888
        and bazarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr tv volume
      stat:
        path: /srv/my_usenet/bazarr/tv
      register: bazarr_tv_volume_directory
      failed_when: not (
        bazarr_tv_volume_directory.stat.exists
        and bazarr_tv_volume_directory.stat.uid == 777
        and bazarr_tv_volume_directory.stat.gid == 888
        and bazarr_tv_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr movies volume
      stat:
        path: /srv/my_usenet/bazarr/movies
      register: bazarr_movies_volume_directory
      failed_when: not (
        bazarr_movies_volume_directory.stat.exists
        and bazarr_movies_volume_directory.stat.uid == 777
        and bazarr_movies_volume_directory.stat.gid == 888
        and bazarr_movies_volume_directory.stat.mode == '0750'
        )

    - name: Should create nzbhydra2 config volume
      stat:
        path: /srv/my_usenet/nzbhydra2/config
      register: nzbhydra2_config_volume_directory
      failed_when: not (
        nzbhydra2_config_volume_directory.stat.exists
        and nzbhydra2_config_volume_directory.stat.uid == 777
        and nzbhydra2_config_volume_directory.stat.gid == 888
        and nzbhydra2_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create nzbhydra2 downloads volume
      stat:
        path: /srv/my_usenet/nzbhydra2/downloads
      register: nzbhydra2_downloads_volume_directory
      failed_when: not (
        nzbhydra2_downloads_volume_directory.stat.exists
        and nzbhydra2_downloads_volume_directory.stat.uid == 777
        and nzbhydra2_downloads_volume_directory.stat.gid == 888
        and nzbhydra2_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should usenet systemd unit file
      slurp:
        src: /etc/systemd/system/usenet.service
      register: usenet_service_file
      failed_when:
        not usenet_service_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=usenet service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          ExecStartPre=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            pull

          ExecStart=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            up

          ExecStop=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          Restart=always
          RestartSec=60s
          TimeoutSec=3600

    - name: Should open 18080/tcp port
      command: nc -z -w1 localhost 18080
      changed_when: false
      register: netcat_18080
      retries: 300
      delay: 1
      until: netcat_18080 is defined
        and netcat_18080.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 18989/tcp port
      command: nc -z -w1 localhost 18989
      changed_when: false
      register: netcat_18989
      retries: 300
      delay: 1
      until: netcat_18989 is defined
        and netcat_18989.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 17878/tcp port
      command: nc -z -w1 localhost 17878
      changed_when: false
      register: netcat_17878
      retries: 300
      delay: 1
      until: netcat_17878 is defined
        and netcat_17878.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 16767/tcp port
      command: nc -z -w1 localhost 16767
      changed_when: false
      register: netcat_16767
      retries: 300
      delay: 1
      until: netcat_16767 is defined
        and netcat_16767.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 15076/tcp port
      command: nc -z -w1 localhost 15076
      changed_when: false
      register: netcat_15076
      retries: 300
      delay: 1
      until: netcat_15076 is defined
        and netcat_15076.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )
