---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/usenet/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: "3.2"
          services:
            sabnzbd:
              image: ghcr.io/linuxserver/sabnzbd:version-3.1.1
              container_name: sabnzbd
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/config/sabnzbd:/config
                - /srv/my_usenet/downloads:/downloads
                - /srv/my_usenet/incomplete-downloads:/incomplete-downloads
              ports:
                - 127.0.0.1:18080:8080
                - 127.0.0.1:19090:9090
              restart: unless-stopped

            sonarr:
              image: ghcr.io/linuxserver/sonarr:version-2.0.0.5344
              container_name: sonarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              depends_on:
                - sabnzbd
              volumes:
                - /srv/my_usenet/config/sonarr:/config
                - /srv/my_usenet/tv:/tv
                - /srv/my_usenet/downloads:/downloads
              ports:
                - 127.0.0.1:18989:8989
              restart: unless-stopped

            radarr:
              image: ghcr.io/linuxserver/radarr:version-3.0.0.4127
              container_name: radarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/config/radarr:/config
                - /srv/my_usenet/movies:/movies
                - /srv/my_usenet/downloads:/downloads
              ports:
                - 127.0.0.1:17878:7878
              restart: unless-stopped

            lidarr:
              image: ghcr.io/linuxserver/lidarr:version-0.8.0.1928
              container_name: lidarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/config/lidarr:/config
                - /srv/my_usenet/music:/music
                - /srv/my_usenet/downloads:/downloads
              ports:
                - 127.0.0.1:18686:8686
              restart: unless-stopped

            bazarr:
              image: ghcr.io/linuxserver/bazarr:version-v0.9.0.6
              container_name: bazarr
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
                - UMASK_SET=022
              volumes:
                - /srv/my_usenet/config/bazarr:/config
                - /srv/my_usenet/movies:/movies
                - /srv/my_usenet/tv:/tv
              ports:
                - 127.0.0.1:16767:6767
              restart: unless-stopped

            nzbhydra2:
              image: ghcr.io/linuxserver/nzbhydra2:version-v3.5.1
              container_name: nzbhydra2
              environment:
                - PUID=777
                - PGID=888
                - TZ=Europe/London
              volumes:
                - /srv/my_usenet/config/nzbhydra2:/config
                - /srv/my_usenet/downloads:/downloads
              ports:
                - 127.0.0.1:15076:5076
              restart: unless-stopped

    - name: Should create sabnzbd config volume
      stat:
        path: /srv/my_usenet/config/sabnzbd
      register: sabnzbd_config_volume_directory
      failed_when: not (
        sabnzbd_config_volume_directory.stat.exists
        and sabnzbd_config_volume_directory.stat.uid == 777
        and sabnzbd_config_volume_directory.stat.gid == 888
        and sabnzbd_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr config volume
      stat:
        path: /srv/my_usenet/config/sonarr
      register: sonarr_config_volume_directory
      failed_when: not (
        sonarr_config_volume_directory.stat.exists
        and sonarr_config_volume_directory.stat.uid == 777
        and sonarr_config_volume_directory.stat.gid == 888
        and sonarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create radarr config volume
      stat:
        path: /srv/my_usenet/config/radarr
      register: radarr_config_volume_directory
      failed_when: not (
        radarr_config_volume_directory.stat.exists
        and radarr_config_volume_directory.stat.uid == 777
        and radarr_config_volume_directory.stat.gid == 888
        and radarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create lidarr config volume
      stat:
        path: /srv/my_usenet/config/lidarr
      register: lidarr_config_volume_directory
      failed_when: not (
        lidarr_config_volume_directory.stat.exists
        and lidarr_config_volume_directory.stat.uid == 777
        and lidarr_config_volume_directory.stat.gid == 888
        and lidarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create bazarr config volume
      stat:
        path: /srv/my_usenet/config/bazarr
      register: bazarr_config_volume_directory
      failed_when: not (
        bazarr_config_volume_directory.stat.exists
        and bazarr_config_volume_directory.stat.uid == 777
        and bazarr_config_volume_directory.stat.gid == 888
        and bazarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create nzbhydra2 config volume
      stat:
        path: /srv/my_usenet/config/nzbhydra2
      register: nzbhydra2_config_volume_directory
      failed_when: not (
        nzbhydra2_config_volume_directory.stat.exists
        and nzbhydra2_config_volume_directory.stat.uid == 777
        and nzbhydra2_config_volume_directory.stat.gid == 888
        and nzbhydra2_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create downloads volume
      stat:
        path: /srv/my_usenet/downloads
      register: downloads_volume_directory
      failed_when: not (
        downloads_volume_directory.stat.exists
        and downloads_volume_directory.stat.uid == 777
        and downloads_volume_directory.stat.gid == 888
        and downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create incomplete downloads volume
      stat:
        path: /srv/my_usenet/incomplete-downloads
      register: incomplete_downloads_volume_directory
      failed_when: not (
        incomplete_downloads_volume_directory.stat.exists
        and incomplete_downloads_volume_directory.stat.uid == 777
        and incomplete_downloads_volume_directory.stat.gid == 888
        and incomplete_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should create tv volume
      stat:
        path: /srv/my_usenet/tv
      register: tv_volume_directory
      failed_when: not (
        tv_volume_directory.stat.exists
        and tv_volume_directory.stat.uid == 777
        and tv_volume_directory.stat.gid == 888
        and tv_volume_directory.stat.mode == '0755'
        )

    - name: Should create movies volume
      stat:
        path: /srv/my_usenet/movies
      register: movies_volume_directory
      failed_when: not (
        movies_volume_directory.stat.exists
        and movies_volume_directory.stat.uid == 777
        and movies_volume_directory.stat.gid == 888
        and movies_volume_directory.stat.mode == '0755'
        )

    - name: Should create music volume
      stat:
        path: /srv/my_usenet/music
      register: music_volume_directory
      failed_when: not (
        music_volume_directory.stat.exists
        and music_volume_directory.stat.uid == 777
        and music_volume_directory.stat.gid == 888
        and music_volume_directory.stat.mode == '0755'
        )

    - name: Should usenet systemd unit file
      slurp:
        src: /etc/systemd/system/usenet.service
      register: usenet_service_file
      failed_when:
        not usenet_service_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=usenet service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          ExecStartPre=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            pull

          ExecStart=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            up

          ExecStop=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          Restart=always
          RestartSec=60s
          TimeoutSec=3600

    - name: Should open 18080/tcp port
      command: nc -z -w1 localhost 18080
      changed_when: false
      register: netcat_18080
      retries: 300
      delay: 1
      until: netcat_18080 is defined
        and netcat_18080.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 18989/tcp port
      command: nc -z -w1 localhost 18989
      changed_when: false
      register: netcat_18989
      retries: 300
      delay: 1
      until: netcat_18989 is defined
        and netcat_18989.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 17878/tcp port
      command: nc -z -w1 localhost 17878
      changed_when: false
      register: netcat_17878
      retries: 300
      delay: 1
      until: netcat_17878 is defined
        and netcat_17878.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 18686/tcp port
      command: nc -z -w1 localhost 18686
      changed_when: false
      register: netcat_18686
      retries: 300
      delay: 1
      until: netcat_18686 is defined
        and netcat_18686.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 16767/tcp port
      command: nc -z -w1 localhost 16767
      changed_when: false
      register: netcat_16767
      retries: 300
      delay: 1
      until: netcat_16767 is defined
        and netcat_16767.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 15076/tcp port
      command: nc -z -w1 localhost 15076
      changed_when: false
      register: netcat_15076
      retries: 300
      delay: 1
      until: netcat_15076 is defined
        and netcat_15076.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )
