---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible_usenet
      usenet_sabnzbd_http_port: 18080
      usenet_sabnzbd_https_port: 19090
      usenet_sonarr_http_port: 18989
