---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/usenet/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: "3.2"
          services:
            sabnzbd:
              image: sabnzbd/sabnzbd
              container_name: sabnzbd
              volumes:
                - /srv/usenet/sabnzbd/datadir:/datadir
                - /srv/usenet/sabnzbd/media:/media
              ports:
                - 0.0.0.0:18080:8080
              environment:
                - SABNZBD_UID=666
                - SABNZBD_GID=666
              restart: unless-stopped

            sonarr:
              image: ghcr.io/linuxserver/sonarr
              container_name: sonarr
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              depends_on:
                - sabnzbd
              volumes:
                - /srv/usenet/sonarr/config:/config
                - /srv/usenet/sonarr/tv:/tv
                - /srv/usenet/sonarr/downloads:/downloads
              ports:
                - 0.0.0.0:18989:8989
              restart: unless-stopped

    - name: Should create sabnzbd datadir volume
      stat:
        path: /srv/usenet/sabnzbd/datadir
      register: sabnzbd_datadir_volume_directory
      failed_when: not (
        sabnzbd_datadir_volume_directory.stat.exists
        and sabnzbd_datadir_volume_directory.stat.uid == 666
        and sabnzbd_datadir_volume_directory.stat.gid == 666
        and sabnzbd_datadir_volume_directory.stat.mode == '0750'
        )

    - name: Should create sabnzbd media volume
      stat:
        path: /srv/usenet/sabnzbd/media
      register: sabnzbd_media_volume_directory
      failed_when: not (
        sabnzbd_media_volume_directory.stat.exists
        and sabnzbd_media_volume_directory.stat.uid == 666
        and sabnzbd_media_volume_directory.stat.gid == 666
        and sabnzbd_media_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr config volume
      stat:
        path: /srv/usenet/sonarr/config
      register: sonarr_config_volume_directory
      failed_when: not (
        sonarr_config_volume_directory.stat.exists
        and sonarr_config_volume_directory.stat.uid == 666
        and sonarr_config_volume_directory.stat.gid == 666
        and sonarr_config_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr tv volume
      stat:
        path: /srv/usenet/sonarr/tv
      register: sonarr_tv_volume_directory
      failed_when: not (
        sonarr_tv_volume_directory.stat.exists
        and sonarr_tv_volume_directory.stat.uid == 666
        and sonarr_tv_volume_directory.stat.gid == 666
        and sonarr_tv_volume_directory.stat.mode == '0750'
        )

    - name: Should create sonarr downloads volume
      stat:
        path: /srv/usenet/sonarr/downloads
      register: sonarr_downloads_volume_directory
      failed_when: not (
        sonarr_downloads_volume_directory.stat.exists
        and sonarr_downloads_volume_directory.stat.uid == 666
        and sonarr_downloads_volume_directory.stat.gid == 666
        and sonarr_downloads_volume_directory.stat.mode == '0750'
        )

    - name: Should usenet systemd unit file
      slurp:
        src: /etc/systemd/system/usenet.service
      register: usenet_service_file
      failed_when:
        not usenet_service_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=usenet service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          ExecStartPre=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            pull

          ExecStart=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            up

          ExecStop=/usr/local/bin/docker-compose \
            --project-directory /opt/usenet/docker \
            --file /opt/usenet/docker/docker-compose.yml \
            --project-name usenet \
            down \
            --remove-orphans

          Restart=always
          RestartSec=60s
          TimeoutSec=3600

    - name: Should open 18080/tcp port
      command: nc -z -w1 localhost 18080
      changed_when: false
      register: netcat_18080
      retries: 300
      delay: 1
      until: netcat_18080 is defined
        and netcat_18080.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

    - name: Should open 18989/tcp port
      command: nc -z -w1 localhost 18989
      changed_when: false
      register: netcat_18989
      retries: 300
      delay: 1
      until: netcat_18989 is defined
        and netcat_18989.rc == 0
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )
