---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/usenext/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: 3.2
          services:
            sabnzbd:
              image: sabnzbd/sabnzbd
              container_name: sabnzbd
              volumes:
                - /srv/usenet/sabnzbd/datadir:/datadir
                - /srv/usenet/sabnzbd/media:/media
              ports:
                - 0.0.0.0:8080:8080
              environment:
                - SABNZBD_UID=666
                - SABNZBD_GID=666
              restart: unless-stopped

            sonarr:
              image: ghcr.io/linuxserver/sonarr
              container_name: sonarr
              environment:
                - PUID=666
                - PGID=666
                - TZ=Europe/London
                - UMASK_SET=022
              depends_on:
                - sabnzbd
              volumes:
                - /srv/usenet/sonarr/config:/config
                - /srv/usenet/sonarr/tv:/tv
                - /srv/usenet/sonarr/downloads:/downloads
              ports:
                - 0.0.0.0:8989:8989
              restart: unless-stopped
